### ISSUE TITLE
Releasing 3.6.2

### ISSUE THREAD

**Issue by swistak35** [savonrb/wasabi#106]
Would it be possible to release next version?
Especially that it contain fixes for regressions (i.e. 665e78d713ef051ee4bae2dc5e2b1aa135916a17)
Can I help somehow? Even preparing a PR with bumped version / gemspec changed etc.?

**Comment by olleolleolle** [comment]
- Find CHANGELOG from: https://github.com/savonrb/wasabi/compare/v3.6.1...master

**Comment by swistak35** [comment]
@olleolleolle I don't understand what you suggesting. Should I help with changelog somehow?

**Comment by olleolleolle** [comment]
@swistak35 What is needed to prepare the release is "make a CHANGELOG edit under an _Unreleased_ heading, covering each important note from the range of commits".

All the other version updating etc, is automated.

**Comment by berkos** [comment]
Hello everyone, thanks for your great work on the gem.
I was wondering if there was anything pending for the [unreleased changes](https://github.com/savonrb/wasabi/blob/master/CHANGELOG.md#unreleased) to be released in RubyGems under a new version.

Thanks for your help again. 🙏

**Comment by yolk** [comment]
Any update on this? Any way to help getting 3.6.2 released?

**Comment by olleolleolle** [comment]
@yolk Thanks for maintaining valvat! 

I, uh, I _think_ we are ready for a new release. Last time I looked, I had to repair the CI, now let's see.

After a few rounds of futzing with it, we have a 3.7.0. I will now close this Issue, thanks everyone.

Please do report any misbehaviour with the new version!

**Comment by yolk** [comment]
@olleolleolle Updating to v3.7.0 seems to fix the issue with valvat. Thanks a lot for your superquick reaction!

**Comment by olleolleolle** [comment]
Thanks again for checking that it worked!
