### ISSUE TITLE
using a vulnerable version nokogiri

### ISSUE THREAD

**Issue by mukhumaev** [savonrb/wasabi#112]
nokogiri < 1.13.9 has vulnerabilities
https://github.com/sparklemotion/nokogiri/security/advisories/GHSA-2qc6-mcvw-92cw

**Comment by pcai** [comment]
thanks, mind opening a pr?

**Comment by mukhumaev** [comment]
https://github.com/savonrb/wasabi/pull/113
done

**Comment by pcai** [comment]
Thank you! Merged
