### ISSUE TITLE
4.0 release breaks integration with `style="rpc"` operations

### ISSUE THREAD

**Issue by hss-mateus** [savonrb/wasabi#118]
If I understand it correctly, PR #114 added a check in the `style` attribute of an operation to know if it's an `document`.

https://github.com/savonrb/wasabi/blob/3bf250213e842c1207d39ee7891288160686574f/lib/wasabi/parser.rb#L147

Apparently, a comparison is missing here, so it's always considering that it's a `document` style.
A solution is to just compare with the desired value:

```ruby
 soap_document = soap_operation["style"] == "document" if soap_operation
```

**Comment by pcai** [comment]
Thanks. Can you provide a pr with a test case please?
