### ISSUE TITLE
Ruby warning - unused variable

### ISSUE THREAD

**Issue by weshatheleopard** [savonrb/wasabi#62]
wasabi/parser.rb:120: warning: assigned but unused variable - root_elements

**Comment by ioquatix** [comment]
```
wasabi-3.5.0/lib/wasabi/parser.rb:308: warning: instance variable @sections not initialized
wasabi-3.5.0/lib/wasabi/parser.rb:89:in `parse_url': warning: URI.unescape is obsolete
wasabi-3.5.0/lib/wasabi/parser.rb:90:in `parse_url': warning: URI.escape is obsolete
```

A few more.

**Comment by olleolleolle** [comment]
These have been repaired, thanks for reporting them!

See #76 and #85 for details. Thanks @chaymaeBZ !

**Comment by olleolleolle** [comment]
Oh, thanks, _again_ for noting an uninitialized instance variable - I think something is being worked on, and perhaps we'll have a fix real soon.
