### ISSUE TITLE
No such file or directory on wsdl:import

### ISSUE THREAD

**Issue by wabiloo** [savonrb/wasabi#71]
Hi,
Using Savon 3.0 (gem 'savon', github: 'savonrb/savon', branch: 'version3' in Gemfile).

I'm trying to use the following public WSDL: [](https://lite.realtime.nationalrail.co.uk/OpenLDBWS/wsdl.aspx?ver=2017-02-02.)
In there there is an import statement: 
`<wsdl:import namespace="http://thalesgroup.com/RTTI/2017-02-02/ldb/" location="rtti_2017-02-02_ldb.wsdl"/>`

On executing the following line:
`	client = Savon.new('https://lite.realtime.nationalrail.co.uk/OpenLDBWS/wsdl.aspx?ver=2017-02-02')
`
I get the following error: 
No such file or directory @ rb_sysopen - rtti_2017-02-02_ldb.wsdl
["/Users/fabre.lambeau/.rvm/gems/ruby-2.4.1/bundler/gems/savon-61e13c61b68e/lib/savon/resolver.rb:15:in `read'", "/Users/fabre.lambeau/.rvm/gems/ruby-2.4.1/bundler/gems/savon-61e13c61b68e/lib/savon/resolver.rb:15:in `resolve'", "/Users/fabre.lambeau/.rvm/gems/ruby-2.4.1/bundler/gems/savon-61e13c61b68e/lib/savon/importer.rb:42:in `import_document'", "/Users/fabre.lambeau/.rvm/gems/ruby-2.4.1/bundler/gems/savon-61e13c61b68e/lib/savon/importer.rb:51:in `block in import_document'", "/Users/fabre.lambeau/.rvm/gems/ruby-2.4.1/bundler/gems/savon-61e13c61b68e/lib/savon/importer.rb:49:in `each'", "/Users/fabre.lambeau/.rvm/gems/ruby-2.4.1/bundler/gems/savon-61e13c61b68e/lib/savon/importer.rb:49:in `import_document'", "/Users/fabre.lambeau/.rvm/gems/ruby-2.4.1/bundler/gems/savon-61e13c61b68e/lib/savon/importer.rb:19:in `import'", "/Users/fabre.lambeau/.rvm/gems/ruby-2.4.1/bundler/gems/savon-61e13c61b68e/lib/savon/wsdl.rb:16:in `initialize'", "/Users/fabre.lambeau/.rvm/gems/ruby-2.4.1/bundler/gems/savon-61e13c61b68e/lib/savon.rb:29:in `new'", "/Users/fabre.lambeau/.rvm/gems/ruby-2.4.1/bundler/gems/savon-61e13c61b68e/lib/savon.rb:29:in `initialize'", "/Users/fabre.lambeau/Documents/Git/HallwayDash/test-smash-2/jobs/train-lst.rb:8:in `new'", "/Users/fabre.lambeau/Documents/Git/HallwayDash/test-smash-2/jobs/train-lst.rb:8:in `block in <top (required)>'", "/Users/fabre.lambeau/.rvm/gems/ruby-2.4.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `trigger_block'", "/Users/fabre.lambeau/.rvm/gems/ruby-2.4.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:204:in `block in trigger'", "/Users/fabre.lambeau/.rvm/gems/ruby-2.4.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `block in trigger_job'", "/Users/fabre.lambeau/.rvm/gems/ruby-2.4.1/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'"]

This seems to be caused by the fact that the imported file has a relative path rather than a full path?
The file does exist at https://lite.realtime.nationalrail.co.uk/OpenLDBWS/rtti_2017-02-02_ldb.wsdl...

Please advise...

**Comment by pcai** [comment]
The "version3" branch of savon was an unstable work-in-progress release that has been abandoned, so there's no support for it, sorry. Are you able to reproduce in a supported savon version? If so, please reopen
